### ISSUE TITLE
Do you still do this?? Am in the unlocking industry and I wish to learn more about the access to Apple GSX

### ISSUE THREAD

**Issue by Wavemansolutions** [UniversityPCCare/gsx-rest-php#10]

**Comment by upccjesse** [comment]
Yes this API is in use daily at our business.

**Comment by Wavemansolutions** [comment]
Hi sorry i replied late, i need access

**Comment by upccjesse** [comment]
You have the source code available to you, but you must have valid credentials from Apple to use it. I cannot help on that front.

**Comment by Wavemansolutions** [comment]
Like what type of credential

**Comment by upccjesse** [comment]
You have to be an Apple Authorized Service Provider. https://support.apple.com/en-lamr/aasp-program

**Comment by Wavemansolutions** [comment]
of a truth i have been trying to get apple ATLAS Certificates since 2017
but cant get one.
