### ISSUE TITLE
Implement SOAP API

### ISSUE THREAD

**Issue by upccjesse** [UniversityPCCare/gsx-rest-php#2]
I had seen it mentioned in the recommended workflow in eServiceCentral documentation but it didn't dawn on me until now that the SOAP API is still valid for certain calls (like fetching invoices). I implemented a quick-and-dirty patch locally to make sure it works and it does. I'll need to include the following:

- A separate certificate for the SOAP API (confirmed it does not work with the certificate generated for the REST API) along with its credentials
- The WSDL file for the SOAP API
- Various parameters that were present in the old GSX SOAP Library, including: languageCode ("en"), userTimeZone, environment ("it" or "ut"), region ("am" for America).
- Like the GSXHandler->curlSend function, I'll need a GSXHandler->soapSend function. Any API calls that need to use the SOAP API will use this function.

Remember that SOAP responses are formatted like:
```<EndpointName>Response => lookupRequestData => <data>```

**Comment by upccjesse** [comment]
I've implemented the basis of the SOAP API, and one function for downloading invoices.

TODO: Add the rest of the legacy SOAP API calls as defined in the "Recommended Flow" guide from eServiceCentral.

**Comment by icep87** [comment]
This year the SOAP API will be removed, the rollout should start in the coming months.
