### ISSUE TITLE
How to check FMI?

### ISSUE THREAD

**Issue by htn** [UniversityPCCare/gsx-rest-php#5]
I can't find FMI check function, Please tell me where I need to find it?

**Comment by icep87** [comment]
The FMI is part of the warranty lookup.

**Comment by htn** [comment]
Thank icep87,
Are you sure about that?
I looked in the source code and didn't see any warranty lookup function.
Please show me function name in code, I tried running ProductDetails($sn) function but no FMI info.

**Comment by icep87** [comment]
Sorry, my bad it's in the repair/eligibility request. 

The response should look like this if FMI is active: 

`{
 "eligibilityDetails": {
  "outcome": [
   {
    "action": "WARNING",
    "reasons": [
     {
      "type": "WARNING",
      "messages": [
       "Find My for this device is active. Find My must be turned off for non-accessory repairs. See OP987 for details."
      ]
     }
    ]
   },
   {
    "reasons": [
     {
      "type": "REPAIR_TYPE",
      "messages": [
       "MRI or Serial Number Reader diagnostics are required to proceed with a repair."
      ],
      "repairOptions": [
       {
        "option": "SVNR",
        "priority": 1,
        "subOption": "NTF"
       },
       {
        "option": "SVNR",
        "priority": 2,
        "subOption": "SRC"
       }
      ]
     }
    ]
   }
  ],
  "coverageCode": "OO",
  "coverageDescription": "Out Of Warranty (No Coverage)",
  "technicianMandatory": false
 }
}`

**Comment by truonggiang0710** [comment]
@icep87 @htn  how about the MDM lock status?

**Comment by htn** [comment]
Thank icep87 so much.
Based on your instructions, I got the FMI information.

**Comment by truonggiang0710** [comment]
@icep87 @htn  how about the MDM lock status? I attach the serial of the MDM phone C7CZD1NFN73T.

**Comment by icep87** [comment]
MDM status has never been provided in GSX. So there is no API for that. 
It’s completely separate backends.

**Comment by truonggiang0710** [comment]
@icep87 Are you sure about that? I see a lot of websites can check MDM status over the serial number.

**Comment by icep87** [comment]
Hi, 

Yes, I’m sure that they are not providing this.

**Comment by truonggiang0710** [comment]
@icep87 ohm, Do you know how to check MDM status over the serial number?

**Comment by icep87** [comment]
No, I can’t say that I do. Especially as MDM is an individual solution.

**Comment by truonggiang0710** [comment]
@icep87 Thank you very much. I will find out.

**Comment by icep87** [comment]
@upccjesse I think this ticket can be closed.

**Comment by htn** [comment]
@icep87 
Today I checked again, everything is 404 not found error.
Even the get activation token from Apple website returns 404 not found (http://gsx2.apple.com/gsx/api/login)
What's going on?

**Comment by icep87** [comment]
The link to login token is: https://login-partner-connect.apple.com/api/login <https://login-partner-connect.apple.com/api/login>

And you have to use https in the url. 

Please check the documentation from GSX API for any changes in the URL.

**Comment by htn** [comment]
Thanks @icep87 
I got the activation token and auth token.
But i get FMI from https://api-partner-connect.apple.com/gsx/api/repair/eligibility => 404 not found.
Can you tell me what am I doing wrong?

**Comment by icep87** [comment]
Did you change the base url in the config file? 

In the code the base url is: https://partner-connect.apple.com/gsx/api <https://partner-connect.apple.com/gsx/api>

If you are coding outside of the script just use the eservice central documentation for everything.

**Comment by htn** [comment]
Hi @icep87 
I used
https://partner-connect.apple.com/gsx/api/repair/eligibility => now => 404 not found (Yesterday was fine)
I change to 
https://api-partner-connect.apple.com/gsx/api/repair/eligibility => now => 404 not found.
I using gsx-rest-php and edit a little to use it.

**Comment by icep87** [comment]
Works fine here, make sure that you are on connecting from the whitelisted IP. 

Otherwise contact GSX WebServices team.

**Comment by enniskeane** [comment]
Hi guys. Link working fine i checked already nice info this. Maybe know what link possible to check other info full any apple device ? Because this link  https://api-partner-connect.apple.com/gsx/api/repair/eligibility got this info only `IMEI Number: 3539221061XXXXX
Model: iPhone 11 Pro Max
Loaner Device: No
Replaced Device: No
AppleCare Eligible: No
Valid Purchase Date: Yes
Activation Status: Activated
Registration Status: Registered
Telephone Technical Support: Expired
Repairs and Service Coverage: Expired
Repairs and Service Expired By: 1 Year 9 Months and 16 Days
Repairs and Service Expiration Date: 2020-12-21
Estimated Purchase Date: 2019-12-22
Warranty Status: Out Of Warranty`

**Comment by enniskeane** [comment]
What other link possible to got it simlock find my iphone or other status info or got full gsx info maybe or sold by etc ?

**Comment by agenda1t** [comment]
What other link possible to got it simlock find my iphone or other status info or got full gsx info maybe or sold by etc ?

**Comment by enniskeane** [comment]
I Would you like to know how can i got api token ? I have a developer account but this link said i'm not authorized Partner API Token Portal so anyone know how can i add for check any apple device info please let me know or made me api php i will pay for that if price ok and api working 100% any time instant to check any device ...
