### ISSUE TITLE
Fatal error: Uncaught Error: Class 'UPCC\PDOHandler' not found in

### ISSUE THREAD

**Issue by istore-dev** [UniversityPCCare/gsx-rest-php#6]
Fatal error: Uncaught Error: Class 'UPCC\PDOHandler' not found in

**Comment by upccjesse** [comment]
Need more info. Sounds like an installation issue?

**Comment by istore-dev** [comment]
Fatal error: Uncaught Error: Class 'UPCC\PDOHandler' not found in /Applications/MAMP/gsx-rest-php/src/GSXHandler.php:48 Stack trace: #0 /Applications/MAMP/gsx-rest-php/tests/test.php(9): UPCC\GSXHandler->__construct('XXX...', 'XXX') #1 {main} thrown in /Applications/MAMP/gsx-rest-php/src/GSXHandler.php on line 48

**Comment by upccjesse** [comment]
Things to consider:

1. `require` autoload.php if using composer
2. use fully qualified namespace `UPCC\GSXHandler` or use `use` instead.
3. check that `PDOHandler.php` actually does exist in the same directory as `GSXHandler.php`.

It's trying to tell you that, for whatever reason, the `GSXHandler` class can't find the `PDOHandler` class. This is usually an issue with either missing `autoload.php` or not qualifying class names (directly when called, or via `use`)
